name: EmotesPlugin
version: '${project.version}'
main: liven.emotesplugin.EmotesPlugin
api-version: 1.18
authors: [ Liven ]
description: Simple Plugin adds Animated Emotes
commands:
  emotes:
    description: Main command for emotes plugin
    usage: /<command> <arg1>
    permission: emotesplugin.command.emotes
